# Generated by Django 5.2.15 on 2026-06-28 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='is_hm',
            field=models.BooleanField(default=False),
        ),
    ]
