# Generated by Django 5.2.15 on 2026-06-28 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_leave_substitutiontask_delete_substitution'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='is_processed',
            field=models.BooleanField(default=False),
        ),
    ]
